### ISSUE TITLE
super-sast-artifact does not have write permissions on /code

### ISSUE THREAD

**Issue by DrPlumcake** [DrPlumcake/super-sast-artifact#24]
## Currently:
- super-sast-action goes into failure because the `os.mkdir()` call can't resolve successfully. 
- This is due to the missing write privilege of the User on the /code directory.

## I Expect:
- super-sast-action write permissions on /code
- user MUST NOT be root or `UID=0`

**Comment by ioggstream** [comment]
See https://github.com/DrPlumcake/super-sast-artifact/actions/runs/6894975901/job/18757937647#step:5:10

1. in case of errors, the action must fail
